locales = [ "de", "es", "fr", "fy-NL", "nl", "pl", "pt-BR",]
[[paths]]
reference = "templates/pages/homepage.pot"
l10n = "locales/{locale}/pages/homepage.po"
locales = [ "de", "es", "fr", "fy-NL", "nl", "pl", "pt-BR",]

[[paths]]
reference = "templates/snippets/wagtailpages.FocusArea/3-shape-the-agenda.pot"
l10n = "locales/{locale}/snippets/wagtailpages.FocusArea/3-shape-the-agenda.po"
locales = [ "de", "es", "fr", "fy-NL", "nl", "pl", "pt-BR",]

[[paths]]
reference = "templates/snippets/wagtailpages.FocusArea/2-connect-leaders.pot"
l10n = "locales/{locale}/snippets/wagtailpages.FocusArea/2-connect-leaders.po"
locales = [ "de", "es", "fr", "fy-NL", "nl", "pl", "pt-BR",]

[[paths]]
reference = "templates/snippets/wagtailpages.FocusArea/1-rally-citizens.pot"
l10n = "locales/{locale}/snippets/wagtailpages.FocusArea/1-rally-citizens.po"
locales = [ "de", "es", "fr", "fy-NL", "nl", "pl", "pt-BR",]

[[paths]]
reference = "templates/pages/homepage/what-we-do.pot"
l10n = "locales/{locale}/pages/homepage/what-we-do.po"
locales = [ "de", "es", "fr", "fy-NL", "nl", "pl", "pt-BR",]

